name: Multiconfig Build

on: push
  
jobs:
    build:
      runs-on: macos-latest
  
      steps:
        - name: Clone
          uses: actions/checkout@v2
        - name: Install Packages
          run: |
            export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
            brew install openssl ninja
        - name: Build (x86_64, Release)
          run: |
            mkdir build-X86_64-RELEASE && cd build-X86_64-RELEASE
            cmake -G Ninja -DKERNEL_BUILD_XNU=1 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
            ninja
        - name: Build (x86_64, Development)
          run: |
            mkdir build-X86_64-DEVELOPMENT && cd build-X86_64-DEVELOPMENT
            cmake -G Ninja -DKERNEL_BUILD_XNU=1 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_BUILD_TYPE="Development" ..
            ninja
        - name: Build (ARM64, VMAPPLE, Development)
          run: |
              mkdir build-ARM64-VMAPPLE-DEVELOPMENT && cd build-ARM64-VMAPPLE-DEVELOPMENT
              cmake -G Ninja -DKERNEL_BUILD_XNU=1 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DBUILD_ARCH="arm64" -DKERNEL_MACHINE="VMAPPLE" -DCMAKE_BUILD_TYPE="Development" ..
              ninja